### ISSUE TITLE
Cyrillic characters lost in translation

### ISSUE THREAD

**Issue by Ninjasoturi** [WatWowMap/Pogo-Data-Generator#92]
I switched to using the pogo-translations repo instead of PokeMiners and there seems to be something funny going on with RU translations. I don't speak russian, but this seems like a bug. The old ones from PokeMiners' repo are identical to translations in Bulbapedia. Here are two examples, but there are tens of these.

Graveler:
```
-        "RU": "Гравелер"
+        "RU": "Грейвлер"
```
Camerupt:
```
-        "RU": "Камерапт"
+        "RU": "Камерупт"
```

**Comment by TurtIeSocks** [comment]
@Ninjasoturi I couldn't replicate this in latest so I assume something downstream was fixed. Feel free to reopen if you're still having trouble with it. Thanks!
