### ISSUE TITLE
API evolutions should merge with gamemaster

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/Pogo-Data-Generator#98]
Currently gamemaster still overrides API evolutions, which is not good: https://github.com/WatWowMap/Masterfile-Generator/commit/73a89cdbc3eef0f8078f8ba6f56b02d351278845

**Comment by TurtIeSocks** [comment]
I believe this may have been a weird scenario where PokeAPI maybe missed the data for some reason as it has been restored to `baseStats.json`. Closing for now, feel free to reopen if you notice it again.
